### ISSUE TITLE
Unable to deploy as WAR to Tomcat 8+

### ISSUE THREAD

**Issue by amotruk** [camunda/camunda-bpm-spring-boot-starter#109]
Hello

I'm trying to deploy my camunda spring-boot project to cloud tomcat, creating war as shown here (http://docs.spring.io/spring-boot/docs/current/reference/html/howto-traditional-deployment.html)
but during app startup there is error:

```
14-Jul-2016 12:28:33.282 SEVERE [localhost-startStop-1] org.apache.catalina.core.ContainerBase.addChildInternal ContainerBase.addChild: start: 
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/camunda-bpm-spring-boot-starter-example-webapp-1.3.5.RELEASE]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:158)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at org.camunda.bpm.spring.boot.starter.webapp.filter.LazyFilterRuntimeListener.init(LazyFilterRuntimeListener.java:51)
	at org.camunda.bpm.spring.boot.starter.webapp.filter.LazyFilterRuntimeListener.finished(LazyFilterRuntimeListener.java:43)
	at org.springframework.boot.SpringApplicationRunListeners.callFinishedListener(SpringApplicationRunListeners.java:79)
	at org.springframework.boot.SpringApplicationRunListeners.finished(SpringApplicationRunListeners.java:72)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:309)
	at org.springframework.boot.context.web.SpringBootServletInitializer.run(SpringBootServletInitializer.java:149)
	at org.springframework.boot.context.web.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:129)
	at org.springframework.boot.context.web.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:85)
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:169)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5167)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
	... 10 more

14-Jul-2016 12:28:33.284 SEVERE [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Error deploying web application archive D:\apache-tomcat-8.5.4\webapps\camunda-bpm-spring-boot-starter-example-webapp-1.3.5.RELEASE.war
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/camunda-bpm-spring-boot-starter-example-webapp-1.3.5.RELEASE]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:728)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

According to this: the problem is probably in org.camunda.bpm.spring.boot.starter.webapp.filter.LazyFilterRuntimeListener class.

Can you look at this.
Thanks.

**Comment by jangalinski** [comment]
I never tried the war deployment so far. To save time analysing, could you provide an example project?

**Comment by amotruk** [comment]
Sure.
https://github.com/amotruk/camunda

**Comment by jangalinski** [comment]
@osteinhauer & @hawky-4s-  .... we will probably need someone who is more familiar with all that servlet-int stuff than I am. Can one of you take over?

**Comment by hawky-4s-** [comment]
@amotruk 
Could you please provide more informations on:
* your mvn project (if possible example project without any custom dependencies - only spring / camunda stuff which reproduces the problem)
* cloud tomcat (what is a cloud tomcat? Any Spring-related thing? Didn't find anything)

**Comment by jangalinski** [comment]
@hawky-4s- for example project, see above: https://github.com/amotruk/camunda

**Comment by amotruk** [comment]
@hawky4s

Yes this problem is reproducing on plain tomcat 8.5.4

**Comment by osteinhauer** [comment]
Filters are initialized later when running in non embedded container. So I changed the lazy initialization. Can anybody double check?

**Comment by jangalinski** [comment]
We should have a tomcat/war deployment example. We could provide the tomcat via assembly and start the complete bundle.
