### ISSUE TITLE
NoClassDefFound

### ISSUE THREAD

**Issue by Salmondx** [camunda/camunda-bpm-spring-boot-starter#129]
When i try to start Camunda with webapp starter (```'org.camunda.bpm.extension:camunda-bpm-spring-boot-starter-webapp:1.2.1'```), this exception occurres:
```
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:915)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:871)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1407)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1397)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:153)
	... 6 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/camunda/bpm/cockpit/impl/web/bootstrap/CockpitContainerBootstrap
	at org.camunda.bpm.spring.boot.starter.webapp.CamundaBpmWebappInitializer.onStartup(CamundaBpmWebappInitializer.java:52)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.selfInitialize(EmbeddedWebApplicationContext.java:225)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.access$000(EmbeddedWebApplicationContext.java:85)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext$1.onStartup(EmbeddedWebApplicationContext.java:209)
	at org.springframework.boot.context.embedded.tomcat.TomcatStarter.onStartup(TomcatStarter.java:55)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5292)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	... 6 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.camunda.bpm.cockpit.impl.web.bootstrap.CockpitContainerBootstrap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 common frames omitted
```

Without webapp all works fine.

**Comment by osteinhauer** [comment]
Hi @Salmondx. Would you please provide an example project (on github)?

**Comment by Salmondx** [comment]
@osteinhauer it is in private repo, but i can provide dependencies config:

```groovy
dependencyManagement {
    imports {
        mavenBom 'org.springframework.cloud:spring-cloud-dependencies:Brixton.SR1'
    }
}

dependencies {
    compile('org.camunda.bpm.extension:camunda-bpm-spring-boot-starter:1.2.1')
    compile('com.h2database:h2')
    compile("org.springframework.cloud:spring-cloud-starter-consul-all")
    compile("org.springframework.cloud:spring-cloud-starter-hystrix")
    compile("org.springframework.cloud:spring-cloud-starter-hystrix-dashboard")
    compile("org.springframework.cloud:spring-cloud-starter-zipkin")
}
```

**Comment by shahablaghaei** [comment]
it relates to camunda-webapp.
when i remove the camunda webapp starter from my pom (only use rest starter), it is just ok;
so how can i embed camunda webapps with my spring boot app? :(
any ideas?

**Comment by osteinhauer** [comment]
without providing a complete example it is difficult to help...

**Comment by shahablaghaei** [comment]
[https://github.com/shahablaghaei/simple-spring-camunda](url)

**Comment by osteinhauer** [comment]
I am sorry but your example doesn't reproduce the error you described. The application starts successfully. To fix the test remove `@WebAppConfiguration`.

**Comment by shahablaghaei** [comment]
omg you are right!
it seams i have a problem with my network connection(in iran);
and with a vpn i can now start the project, so thank you!
