### ISSUE TITLE
travis build is failing

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#144]
since jenkins runs through, this might be a timing issue, the test is marked with a 5sec timeout, seems travis takes longer.

trace:

```
2016-09-11 13:27:23.787  WARN 3650 --- [me-limited test] o.s.test.context.TestContextManager      : Caught exception while allowing TestExecutionListener [org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener@a0a9fa5] to process 'after' execution for test: method [public void org.camunda.bpm.spring.boot.starter.example.cloud.simple.SimpleApplicationTest.would_fail_if_process_not_completed_after_5_seconds() throws java.lang.InterruptedException], instance [org.camunda.bpm.spring.boot.starter.example.cloud.simple.SimpleApplicationTest@316e8e60], exception [null]

java.lang.IllegalStateException: The ApplicationContext loaded for [[WebMergedContextConfiguration@38499e48 testClass = SimpleApplicationTest, locations = '{}', classes = '{class org.camunda.bpm.spring.boot.starter.example.cloud.simple.SimpleApplication, class org.camunda.bpm.spring.boot.starter.example.cloud.simple.SimpleApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[org.springframework.boot.test.context.SpringBootTestContextCustomizer@5652f555, org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@794b435f, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]]] is not active. Ensure that the context has not been closed programmatically.
	at org.springframework.util.Assert.state(Assert.java:392) ~[spring-core-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:87) ~[spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener.afterTestMethod(MockRestServiceServerResetTestExecutionListener.java:35) ~[spring-boot-test-autoconfigure-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.springframework.test.context.TestContextManager.afterTestMethod(TestContextManager.java:319) ~[spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:94) [spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292) [junit-4.12.jar:4.12]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]

2016-09-11 13:27:23.788  WARN 3650 --- [me-limited test] o.s.test.context.TestContextManager      : Caught exception while allowing TestExecutionListener [org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener@4565a70a] to process 'after' execution for test: method [public void org.camunda.bpm.spring.boot.starter.example.cloud.simple.SimpleApplicationTest.would_fail_if_process_not_completed_after_5_seconds() throws java.lang.InterruptedException], instance [org.camunda.bpm.spring.boot.starter.example.cloud.simple.SimpleApplicationTest@316e8e60], exception [null]

java.lang.IllegalStateException: The ApplicationContext loaded for [[WebMergedContextConfiguration@38499e48 testClass = SimpleApplicationTest, locations = '{}', classes = '{class org.camunda.bpm.spring.boot.starter.example.cloud.simple.SimpleApplication, class org.camunda.bpm.spring.boot.starter.example.cloud.simple.SimpleApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[org.springframework.boot.test.context.SpringBootTestContextCustomizer@5652f555, org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@794b435f, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]]] is not active. Ensure that the context has not been closed programmatically.
	at org.springframework.util.Assert.state(Assert.java:392) ~[spring-core-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:87) ~[spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener.afterTestMethod(ResetMocksTestExecutionListener.java:49) ~[spring-boot-test-1.4.0.RELEASE.jar:1.4.0.RELEASE]
	at org.springframework.test.context.TestContextManager.afterTestMethod(TestContextManager.java:319) ~[spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:94) [spring-test-4.3.2.RELEASE.jar:4.3.2.RELEASE]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298) [junit-4.12.jar:4.12]
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292) [junit-4.12.jar:4.12]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 38.256 sec <<< FAILURE!
would_fail_if_process_not_completed_after_5_seconds(org.camunda.bpm.spring.boot.starter.example.cloud.simple.SimpleApplicationTest)  Time elapsed: 1.577 sec  <<< ERROR!
java.lang.IllegalStateException: The ApplicationContext loaded for [[WebMergedContextConfiguration@38499e48 testClass = SimpleApplicationTest, locations = '{}', classes = '{class org.camunda.bpm.spring.boot.starter.example.cloud.simple.SimpleApplication, class org.camunda.bpm.spring.boot.starter.example.cloud.simple.SimpleApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[org.springframework.boot.test.context.SpringBootTestContextCustomizer@5652f555, org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@794b435f, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]]] is not active. Ensure that the context has not been closed programmatically.
	at org.springframework.util.Assert.state(Assert.java:392)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:87)
	at org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener.afterTestMethod(MockRestServiceServerResetTestExecutionListener.java:35)
	at org.springframework.test.context.TestContextManager.afterTestMethod(TestContextManager.java:319)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:94)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)


Results :

Tests in error: 
  would_fail_if_process_not_completed_after_5_seconds(org.camunda.bpm.spring.boot.starter.example.cloud.simple.SimpleApplicationTest): The ApplicationContext loaded for [[WebMergedContextConfiguration@38499e48 testClass = SimpleApplicationTest, locations = '{}', classes = '{class org.camunda.bpm.spring.boot.starter.example.cloud.simple.SimpleApplication, class org.camunda.bpm.spring.boot.starter.example.cloud.simple.SimpleApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[org.springframework.boot.test.context.SpringBootTestContextCustomizer@5652f555, org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@794b435f, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]]] is not active. Ensure that the context has not been closed programmatically.
```

**Comment by jangalinski** [comment]
Wow, that was a tough one. Thanks!
