### ISSUE TITLE
webjar ee workaround fails with spring boot 1.4

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#158]
Since the spring jar layout changed, I am getting:

```
at de.swm.basisanwendungen.pal.eltuel.webapp.ElektronischeTuelWebApplication.main(ElektronischeTuelWebApplication.java:24) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:na]
Caused by: java.lang.RuntimeException: javax.servlet.ServletException: Could not read security filter config file '/securityFilterRules.json': no such resource in servlet context.
	at org.camunda.bpm.spring.boot.starter.webapp.filter.LazyDelegateFilter.lazyInit(LazyDelegateFilter.java:32) ~[camunda-bpm-spring-boot-starter-webapp-1.3.0.jar:1.3.0]
	at org.camunda.bpm.spring.boot.starter.webapp.filter.LazyInitRegistration.lazyInit(LazyInitRegistration.java:46) ~[camunda-bpm-spring-boot-starter-webapp-1.3.0.jar:1.3.0]
	at org.camunda.bpm.spring.boot.starter.webapp.filter.LazyInitRegistration.setApplicationContext(LazyInitRegistration.java:64) ~[camunda-bpm-spring-boot-starter-webapp-1.3.0.jar:1.3.0]
	at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:121) ~[spring-context-4.3.3.RELEASE.jar:4.3.3.RELEASE]
```

**Comment by jangalinski** [comment]
arg. just forgot a dependency

**Comment by benhoffmann** [comment]
Which dependency did you forget? I just ran into the same problem....

**Comment by jangalinski** [comment]
Sorry, I cannot remember what I did back then ... do you have this in your pom?

```
 <dependency>
            <groupId>org.camunda.bpm.webapp</groupId>
            <artifactId>camunda-webapp-ee-plugins</artifactId>
            <version>${camunda.version}</version>
            <type>jar</type>
            <classifier>classes</classifier>
        </dependency>
```

**Comment by benhoffmann** [comment]
Got it working somehow, couldn't really figure out what was wrong. But thanks anyway!

**Comment by hbeaufils** [comment]
For those who might have this problem, this issue can be related to the `camunda.bpm.webapp.webjarClasspath` property (if you did override it). If you define it, just know that, as stated in the [7.10 upgrade documentation](https://docs.camunda.org/manual/latest/update/minor/79-to-710/#changed-webjar-structure) the Webjar structure has changed, and with it, the `securityFilterRules.json` file location.

In the most recent version of the starter, the `WebappProperty` class defines the correct default value for the location, so there's no need to set the property.
