### ISSUE TITLE
Interrupted Exception on jobExecutor when tests finish

### ISSUE THREAD

**Issue by jangalinski** [camunda/camunda-bpm-spring-boot-starter#195]
When the simple test application examples shut down, they through an (seamingly harmless but annoying) exception:

```
2017-06-11 12:36:30.719  WARN 12397 --- [pool-1-thread-1] org.camunda.bpm.engine.jobexecutor       : ENGINE-14010 Interrupted while shutting down the job executor

java.lang.InterruptedException: null
	at java.lang.Object.wait(Native Method) ~[na:1.8.0_131]
	at java.lang.Thread.join(Thread.java:1252) [na:1.8.0_131]
	at java.lang.Thread.join(Thread.java:1326) [na:1.8.0_131]
	at org.camunda.bpm.engine.impl.jobexecutor.JobExecutor.stopJobAcquisitionThread(JobExecutor.java:339) [camunda-engine-7.7.0.jar:7.7.0]
	at org.camunda.bpm.engine.spring.components.jobexecutor.SpringJobExecutor.stopExecutingJobs(SpringJobExecutor.java:71) [camunda-engine-spring-7.7.0.jar:7.7.0]
	at org.camunda.bpm.engine.impl.jobexecutor.JobExecutor.shutdown(JobExecutor.java:90) [camunda-engine-7.7.0.jar:7.7.0]
	at org.camunda.bpm.engine.impl.jobexecutor.JobExecutor.unregisterProcessEngine(JobExecutor.java:125) [camunda-engine-7.7.0.jar:7.7.0]
	at org.camunda.bpm.engine.impl.ProcessEngineImpl.close(ProcessEngineImpl.java:145) [camunda-engine-7.7.0.jar:7.7.0]
	at org.camunda.bpm.engine.spring.ProcessEngineFactoryBean.destroy(ProcessEngineFactoryBean.java:39) [camunda-engine-spring-7.7.0.jar:7.7.0]
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:272) [spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:578) [spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:554) [spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:961) [spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:523) [spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:968) [spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1030) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1006) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:958) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.boot.SpringApplication.close(SpringApplication.java:1178) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.exit(SpringApplication.java:1165) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.camunda.bpm.spring.boot.example.cloud.SimpleApplication.exitApplicationWhenProcessIsFinished(SimpleApplication.java:78) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```

I suppose it would be a good idea to clean up the jobExecutor lifecylce to have a clean shutdown.

I already tried this: 

```
 // this fixes the slow shutdown of the JobExecutor during test (default timeout it 30 seconds)
    @Bean
    DefaultLifecycleProcessor lifecycleProcessor() {
        final DefaultLifecycleProcessor defaultLifecycleProcessor = new DefaultLifecycleProcessor();
        defaultLifecycleProcessor.setTimeoutPerShutdownPhase(1);
        return defaultLifecycleProcessor;
    }
```

but without success

**Comment by sdorokhova** [comment]
Copied to https://app.camunda.com/jira/browse/CAM-8294.
Please continue working on this in Jira.
