### ISSUE TITLE
Gradle webapp-ee: Build failure on resolveCamundaEnterpriseWebjar

### ISSUE THREAD

**Issue by awilhelmer** [camunda/camunda-bpm-spring-boot-starter#253]
I'm using the new gradle camunda-webjar-plugin for my spring boot camunda project. 
But if i add `compile('org.springframework.boot:spring-boot-starter-data-jpa')` i get build errors on copy resources from task resolveCamundaEnterpriseWebjar:

```
Caused by: org.gradle.api.GradleException: Could not copy zip entry C:\Users\Alexander_Wilhelmer\.gradle\caches\modules-2\files-2.1\xml-apis\xml-apis\1.4.01\3789d9fada2d3d458c4ba2de349d48780f381ee3\xml-apis-1.4.01.jar!license/ to 'C:\data\projects\schadenaufnahme\process\build\resources\main\LICENSE'.
        at org.gradle.api.internal.file.AbstractFileTreeElement.copyTo(AbstractFileTreeElement.java:79)
        at org.gradle.api.internal.file.copy.DefaultFileCopyDetails.copyTo(DefaultFileCopyDetails.java:106)
        at org.gradle.api.internal.file.copy.FileCopyAction$FileCopyDetailsInternalAction.processFile(FileCopyAction.java:44)
        at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator$1.maybeVisit(NormalizingCopyActionDecorator.java:98)
        at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator$1.access$000(NormalizingCopyActionDecorator.java:53)
        at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator$1$1.processFile(NormalizingCopyActionDecorator.java:65)
        at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator$1$1.processFile(DuplicateHandlingCopyActionDecorator.java:60)
        at org.gradle.api.internal.file.copy.CopyFileVisitorImpl.processFile(CopyFileVisitorImpl.java:62)
        at org.gradle.api.internal.file.copy.CopyFileVisitorImpl.visitFile(CopyFileVisitorImpl.java:46)
        at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTreeImpl$1.visitFile(AbstractFileTree.java:181)
        at org.gradle.api.internal.file.archive.ZipFileTree.visit(ZipFileTree.java:91)
        ... 96 more
Caused by: org.gradle.api.UncheckedIOException: Cannot create directory 'C:\data\projects\schadenaufnahme\process\build\resources\main\LICENSE' as it already exists, but is not a directory
```

**Comment by awilhelmer** [comment]
I deleted the LICENSE file in build/resources/main and created a LICENSE directory. So i get the next error: 
```
Caused by: org.gradle.api.GradleException: Could not copy zip entry C:\Users\Alexander_Wilhelmer\.gradle\caches\modules-2\files-2.1\org.apache.tomcat\tomcat-jdbc\8.5.14\1303e59a4b69dd126454132cf6f6bc2d0fbd90ec\tomcat-jdbc-8.5.14.jar!LICENSE to 'C:\data\projects\schadenaufnahme\process\build\resources\main\LICENSE'.
        at org.gradle.api.internal.file.AbstractFileTreeElement.copyTo(AbstractFileTreeElement.java:79)
        at org.gradle.api.internal.file.copy.DefaultFileCopyDetails.copyTo(DefaultFileCopyDetails.java:106)
        at org.gradle.api.internal.file.copy.FileCopyAction$FileCopyDetailsInternalAction.processFile(FileCopyAction.java:44)
        at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator$1$1.processFile(NormalizingCopyActionDecorator.java:66)
        at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator$1$1.processFile(DuplicateHandlingCopyActionDecorator.java:60)
        at org.gradle.api.internal.file.copy.CopyFileVisitorImpl.processFile(CopyFileVisitorImpl.java:62)
        at org.gradle.api.internal.file.copy.CopyFileVisitorImpl.visitFile(CopyFileVisitorImpl.java:46)
        at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTreeImpl$1.visitFile(AbstractFileTree.java:181)
        at org.gradle.api.internal.file.archive.ZipFileTree.visit(ZipFileTree.java:91)
        ... 96 more
Caused by: java.io.FileNotFoundException: C:\data\projects\schadenaufnahme\process\build\resources\main\LICENSE (Zugriff verweigert)
```

It seems there are some problems to handle License files and directories from different dependencies.

**Comment by zambrovski** [comment]
Hi Alex,

I can't reproduce the described behaviour. What OS are you using?
I tried it on Windows 10 Linux Subsystem and on Windows 10 cygwin.

Kind regards,

Simon

**Comment by stefanzilske** [comment]
Hi Alex,

Just tried the same on macOS 10.12.5 and don't have any issues using it together with the spring-boot-starter-data-jpa dependency.

Can you maybe post your Gradle file, so we can see how exactly you use the plugin?

Cheers,
Stefan

**Comment by awilhelmer** [comment]
Hello,

okay than it is a problem with my gradle configuration. I am using Win 7 x64. Gradle 3.4.1
I fixed this problem with adding the following configuration:

```
configurations {
    camundaEE {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-data-jpa'
    }
}
```

But i guess in my case the plugin copies too much data and i don't know why. We are using a base Gradle file with some setup. But my base Gradle structure looks similar to:

```
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
    }

    dependencies {
        classpath 'org.camunda.bpm.extension.springboot.gradle:camunda-bpm-spring-boot-webjar-gradle-plugin:2.1.0'
    }
}


plugins {
    id "java"
    id "org.springframework.boot" version '1.5.3.RELEASE'
    id "io.spring.dependency-management" version "1.0.2.RELEASE"
    id 'net.researchgate.release' version '2.4.0'
}


apply plugin: 'camunda-webjar-plugin'
apply plugin: 'project-report'

camundaWebjarPlugin {
    camundaVersion = "7.6.3-ee"
}

group = 'xxx'
archivesBaseName = 'xxx'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8
targetCompatibility = 1.8



repositories {
    mavenLocal()
    mavenCentral()
    maven {
        credentials {
            username 'xxx'
            password 'xxx'
        }
        url 'https://app.camunda.com/nexus/content/repositories/camunda-bpm-ee'
    }
    maven { url "https://repo.spring.io/milestone" }
}

dependencyManagement {
    imports {
        mavenBom 'org.camunda.bpm.extension.springboot:camunda-bpm-spring-boot-starter-bom:2.1.0'
        mavenBom 'org.springframework.boot:spring-boot-dependencies:1.5.3.RELEASE'
        mavenBom 'org.camunda.bpm:camunda-bom:7.6.3-ee'
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:Dalston.RELEASE"
    }
}

configurations {
    xjc
    camundaEE {
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-data-jpa'
    }
    all {
        exclude group: 'org.apache.logging.log4j'
    }
}
dependencies {
    compile 'org.camunda.bpm.extension.springboot:camunda-bpm-spring-boot-starter-webapp-core' 
    compile 'org.camunda.bpm.webapp:camunda-webapp-ee-plugins:7.6.3-ee:classes'
    compile('com.microsoft.sqlserver:mssql-jdbc') {
        exclude group: 'com.sun.jersey'
    }
    compile 'com.h2database:h2' // TODO for tests

    //<!--   S P I N   -->
    compile "org.camunda.spin:camunda-spin-dataformat-all"
    compile "org.camunda.bpm:camunda-engine-plugin-spin"

    // Spring
    compile "org.springframework:spring-jms"
    compile 'org.springframework:spring-aop'
    compile 'org.springframework.boot:spring-boot-starter-mail'
    compile 'org.springframework.boot:spring-boot-starter-thymeleaf'
    compile('org.springframework.boot:spring-boot-starter-data-jpa')
    compile('org.springframework.security:spring-security-config')
    compile('org.springframework.cloud:spring-cloud-starter-oauth2')
    // OTHER
    compile "org.apache.activemq:activemq-client:5.14.2"
    compile "org.apache.activemq:activemq-pool:5.14.2"
    compile 'org.aspectj:aspectjweaver'
}

jar dependsOn resolveCamundaEnterpriseWebjar
...
```

**Comment by stefanzilske** [comment]
Hey Alex,

try with version 2.1.2 of the camunda-spring-boot-starter and the plugin please, because it includes a fix, which the affects the compile classpath.

Let me know if that helps!

Cheers.
Stefan

**Comment by awilhelmer** [comment]
Hey Stefan,

the building time is very fast with 2.1.2 (Updated both, classpath dependencies in buildscript and the mavenBom). But i get errors on start up:

```
13:44:29.708 INFO  [o.s.s.c.ThreadPoolTaskExecutor] :  Initializing ExecutorService  'camundaTaskExecutor'
13:44:29.878 WARN  [o.s.b.c.e.AnnotationConfigEmbeddedWebApplicationContext] :  Exception encountered during context initialization - cancelling refresh attempt: org.
springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'processEngineHealthIndicator' defined in class path resource [org/camunda
/bpm/spring/boot/starter/CamundaBpmActuatorConfiguration.class]: Unsatisfied dependency expressed through method 'processEngineHealthIndicator' parameter 0; nested ex
ception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'processEngineFactoryBean': FactoryBean threw exception on object cr
eation; nested exception is java.lang.IllegalStateException: Task already scheduled or cancelled
13:44:29.878 INFO  [o.s.s.c.ThreadPoolTaskExecutor] :  Shutting down ExecutorService 'camundaTaskExecutor'
13:44:29.938 INFO  [o.s.s.c.ThreadPoolTaskExecutor] :  Shutting down ExecutorService 'threadPoolTaskExecutor'
13:44:29.938 INFO  [o.s.o.j.LocalContainerEntityManagerFactoryBean] :  Closing JPA EntityManagerFactory for persistence unit 'default'
13:44:29.948 ERROR [o.a.c.c.C.[.[.[/]] :  Failed to destroy the filter named [Engines Filter] of type [org.camunda.bpm.spring.boot.starter.webapp.filter.LazyProcessEn
ginesFilter]
java.lang.NullPointerException: null
        at org.camunda.bpm.spring.boot.starter.webapp.filter.LazyDelegateFilter.destroy(LazyDelegateFilter.java:49)
        at org.apache.catalina.core.ApplicationFilterConfig.release(ApplicationFilterConfig.java:312)
        at org.apache.catalina.core.StandardContext.filterStop(StandardContext.java:4623)
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5421)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1435)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1424)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Greets,
Alex

**Comment by awilhelmer** [comment]
And i'm using this as Bootstrap Class. With own CamundaConfig class importing `@Import({ SpringProcessEngineServicesConfiguration.class })`

```
@org.springframework.boot.autoconfigure.SpringBootApplication(scanBasePackages = { "my.base.package", "other.config.package" })
public class WebApp extends SpringBootServletInitializer {

   @Autowired
   private RuntimeService runtimeService;

   public static void main(String[] args) {
      SpringApplication.run(WebApp.class, args);
   }

   @Override
   protected SpringApplicationBuilder configure(SpringApplicationBuilder builder) {
      return builder.sources(WebApp.class);
   }

}
```
Maybe thats the problem now?

**Comment by awilhelmer** [comment]
okay i have fixed it, adding exclude:
`exclude = { CamundaBpmAutoConfiguration.class}`
