### ISSUE TITLE
NoSuchBeanDefinitionException

### ISSUE THREAD

**Issue by whiskeysierra** [camunda/camunda-bpm-spring-boot-starter#27]
Not sure what I'm doing wrong, but if I add the starter as a dependency and try to fire up my application I get this:

```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.camunda.bpm.spring.boot.starter.CamundaBpmProperties] is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:372) ~[spring-beans-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:332) ~[spring-beans-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1060) ~[spring-context-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.camunda.bpm.spring.boot.starter.runlistener.AbstractFinishedWithNoExceptionRunListener.getBean(AbstractFinishedWithNoExceptionRunListener.java:80) ~[camunda-bpm-spring-boot-starter-1.0.0.jar:1.0.0]
	at org.camunda.bpm.spring.boot.starter.runlistener.AbstractFinishedWithNoExceptionRunListener.finished(AbstractFinishedWithNoExceptionRunListener.java:42) ~[camunda-bpm-spring-boot-starter-1.0.0.jar:1.0.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) ~[spring-boot-1.2.7.RELEASE.jar:1.2.7.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) ~[spring-boot-1.2.7.RELEASE.jar:1.2.7.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:126) ~[spring-cloud-context-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:75) ~[spring-cloud-context-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:55) ~[spring-cloud-context-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163) ~[spring-context-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136) ~[spring-context-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:119) ~[spring-context-4.2.2.RELEASE.jar:4.2.2.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:100) ~[spring-boot-1.2.7.RELEASE.jar:1.2.7.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:59) ~[spring-boot-1.2.7.RELEASE.jar:1.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:286) [spring-boot-1.2.7.RELEASE.jar:1.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:969) [spring-boot-1.2.7.RELEASE.jar:1.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:958) [spring-boot-1.2.7.RELEASE.jar:1.2.7.RELEASE]
	at de.zalando.fulfillment.Application.main(Application.java:14) [classes/:?]
Exception in thread "main" org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.camunda.bpm.spring.boot.starter.CamundaBpmProperties] is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:372)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:332)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1060)
	at org.camunda.bpm.spring.boot.starter.runlistener.AbstractFinishedWithNoExceptionRunListener.getBean(AbstractFinishedWithNoExceptionRunListener.java:80)
	at org.camunda.bpm.spring.boot.starter.runlistener.AbstractFinishedWithNoExceptionRunListener.finished(AbstractFinishedWithNoExceptionRunListener.java:42)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:126)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:75)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:55)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:119)
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:100)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:59)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:286)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:969)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:958)
	at de.zalando.fulfillment.Application.main(Application.java:14)
```

Any idea?

**Comment by jangalinski** [comment]
Could you provide an example, please?

**Comment by whiskeysierra** [comment]
I just tried to create a minimal example and that worked. So I'm trying to gradually add the dependencies and configurations that I used before and see where it starts breaking. Pretty weird issue, but it now looks like it's not related to your starter, but rather my project setup.

**Comment by whiskeysierra** [comment]
Can't reproduce it anymore. I'll reopen it in case I find a way.

**Comment by qihaiyan** [comment]
when importing springcloud in gradle like:
    compile("org.springframework.cloud:spring-cloud-starter-zuul")
    compile("org.springframework.cloud:spring-cloud-starter-security")
the error can be reproduecd.
