### ISSUE TITLE
spring boot ee - index.html not found

### ISSUE THREAD

**Issue by cpiepel** [camunda/camunda-bpm-spring-boot-starter#281]
camunda spring boot starter 2.2.0
camunda 7.7.2-ee

If I use camunda with enterprise setup 

		<dependency>
			<groupId>org.camunda.bpm.extension.springboot</groupId>
			<artifactId>camunda-bpm-spring-boot-starter-webapp-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.camunda.bpm.webapp</groupId>
			<artifactId>camunda-webapp-ee-plugins</artifactId>
			<version>${camunda.ee.version}</version>
			<type>jar</type>
			<classifier>classes</classifier>
		</dependency>

i  get the following error.

2017-08-24 12:55:36.090 ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.lang.RuntimeException: java.io.FileNotFoundException: class path resource [app/welcome/index.html] cannot be opened because it does not exist
	at org.camunda.bpm.webapp.impl.security.auth.AuthenticationFilter$1.execute(AuthenticationFilter.java:61)
	at org.camunda.bpm.webapp.impl.security.auth.AuthenticationFilter$1.execute(AuthenticationFilter.java:56)
	at org.camunda.bpm.webapp.impl.security.SecurityActions.runWithAuthentications(SecurityActions.java:38)

**Comment by cpiepel** [comment]
i did not include the maven plugins. sorry. 
actual i had to set 
`
<configuration>
   <camundaVersion>${camunda.ee.version}</camundaVersion>
</configuration>
`
for the webjar-maven-plugin
