### ISSUE TITLE
strange behavior when using 7.4.0 history level auto feature

### ISSUE THREAD

**Issue by osteinhauer** [camunda/camunda-bpm-spring-boot-starter#30]
When using camunda 7.4.0 in conjunction with supported history level auto there is a strange initialization behavior:

Following `org.camunda.bpm.engine.spring.ProcessEngineFactoryBean` the calls are:

1. `org.camunda.bpm.engine.impl.cfg.ProcessEngineConfigurationImpl.init()`
2. `org.camunda.bpm.engine.impl.SchemaOperationsProcessEngineBuild.determineAutoHistoryLevel(ProcessEngineConfigurationImpl, HistoryLevel)`

This results in configuration elements having `historyLevel == null` and errors when auto deploying:

```
Caused by: org.camunda.bpm.engine.ProcessEngineException: ENGINE-01009 Error while parsing process
	at org.camunda.bpm.engine.impl.bpmn.parser.BpmnParseLogger.parsingProcessException(BpmnParseLogger.java:46) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.bpmn.parser.BpmnParse.execute(BpmnParse.java:298) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.bpmn.deployer.BpmnDeployer.transformDefinitions(BpmnDeployer.java:100) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.AbstractDefinitionDeployer.transformResource(AbstractDefinitionDeployer.java:91) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.AbstractDefinitionDeployer.parseDefinitionResources(AbstractDefinitionDeployer.java:66) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.AbstractDefinitionDeployer.deploy(AbstractDefinitionDeployer.java:56) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.persistence.deploy.DeploymentCache$1.call(DeploymentCache.java:69) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.persistence.deploy.DeploymentCache$1.call(DeploymentCache.java:66) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.interceptor.CommandContext.runWithoutAuthorization(CommandContext.java:553) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.persistence.deploy.DeploymentCache.deploy(DeploymentCache.java:66) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.persistence.entity.DeploymentManager.insertDeployment(DeploymentManager.java:52) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.cmd.DeployCmd.deploy(DeployCmd.java:470) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.cmd.DeployCmd$1.call(DeployCmd.java:137) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.cmd.DeployCmd$1.call(DeployCmd.java:126) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.interceptor.CommandContext.runWithoutAuthorization(CommandContext.java:553) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.cmd.DeployCmd.doExecute(DeployCmd.java:126) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.cmd.DeployCmd.execute(DeployCmd.java:93) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.cmd.DeployCmd.execute(DeployCmd.java:75) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.interceptor.CommandExecutorImpl.execute(CommandExecutorImpl.java:24) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:95) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.spring.SpringTransactionInterceptor$1.doInTransaction(SpringTransactionInterceptor.java:42) ~[camunda-engine-spring-7.4.0.jar:7.4.0]
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133) ~[spring-tx-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	at org.camunda.bpm.engine.spring.SpringTransactionInterceptor.execute(SpringTransactionInterceptor.java:40) ~[camunda-engine-spring-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.interceptor.LogInterceptor.execute(LogInterceptor.java:30) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.RepositoryServiceImpl.deploy(RepositoryServiceImpl.java:92) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.repository.DeploymentBuilderImpl.deploy(DeploymentBuilderImpl.java:207) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.spring.SpringProcessEngineConfiguration.autoDeployResources(SpringProcessEngineConfiguration.java:143) ~[camunda-engine-spring-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.spring.SpringProcessEngineConfiguration.buildProcessEngine(SpringProcessEngineConfiguration.java:62) ~[camunda-engine-spring-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.spring.ProcessEngineFactoryBean.getObject(ProcessEngineFactoryBean.java:51) ~[camunda-engine-spring-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.spring.ProcessEngineFactoryBean.getObject(ProcessEngineFactoryBean.java:31) ~[camunda-engine-spring-7.4.0.jar:7.4.0]
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168) ~[spring-beans-4.2.3.RELEASE.jar:4.2.3.RELEASE]
	... 65 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.camunda.bpm.engine.impl.history.parser.HistoryParseListener.addActivityHandlers(HistoryParseListener.java:224) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.history.parser.HistoryParseListener.parseStartEvent(HistoryParseListener.java:142) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.bpmn.parser.BpmnParse.parseStartEvents(BpmnParse.java:864) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.bpmn.parser.BpmnParse.parseScope(BpmnParse.java:650) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.bpmn.parser.BpmnParse.parseProcess(BpmnParse.java:574) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.bpmn.parser.BpmnParse.parseProcessDefinitions(BpmnParse.java:513) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.bpmn.parser.BpmnParse.parseRootElement(BpmnParse.java:323) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.bpmn.parser.BpmnParse.execute(BpmnParse.java:288) ~[camunda-engine-7.4.0.jar:7.4.0]
	... 94 common frames omitted
```

**Comment by osteinhauer** [comment]
Hi Jan. Can you have a look? I think you are the history level auto master and can give hints or fixes ;)

**Comment by jangalinski** [comment]
Will do.  tonight maybe.

**Comment by saig0** [comment]
Hi. Here is the Jira issue that I already created: https://app.camunda.com/jira/browse/CAM-5164

**Comment by osteinhauer** [comment]
Thx for pointing that out. So the good news is that the starter has its own auto feature which can be used even with older camunda versions.

**Comment by osteinhauer** [comment]
closed because we have a workaround.

**Comment by jangalinski** [comment]
I will have a look into the camunda core 7.4 issues on jira. Seems we missed something when we put this up.
