### ISSUE TITLE
Intégration camunda

### ISSUE THREAD

**Issue by issovic** [camunda/camunda-bpm-spring-boot-starter#357]
Hello,
i m having issues integration camunda bpmn with springboot using oracle 12c , i m always getting error while intializing the database . always shows error creating tables . i m always setting jpa.hibernate. ddl-auto=update 
is there an empty oracle dmp for the process engine database tables ?

Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.sql.SQLSyntaxErrorException: ORA-00942: Table ou vue inexistante

	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectOne(DefaultSqlSession.java:77)
	at org.camunda.bpm.engine.impl.db.sql.DbSqlSession.selectById(DbSqlSession.java:110)
	at org.camunda.bpm.engine.impl.db.entitymanager.DbEntityManager.selectById(DbEntityManager.java:213)
	at org.camunda.bpm.engine.impl.persistence.entity.PropertyManager.findPropertyById(PropertyManager.java:29)
	at org.camunda.bpm.engine.impl.HistoryLevelSetupCommand.checkStartupLockExists(HistoryLevelSetupCommand.java:107)
	at org.camunda.bpm.engine.impl.HistoryLevelSetupCommand.execute(HistoryLevelSetupCommand.java:39)
	at org.camunda.bpm.engine.impl.HistoryLevelSetupCommand.execute(HistoryLevelSetupCommand.java:31)
	at org.camunda.bpm.engine.impl.interceptor.CommandExecutorImpl.execute(CommandExecutorImpl.java:28)
	at org.camunda.bpm.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:107)
	... 45 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: ORA-00942: Table ou vue inexistante

**Comment by jangalinski** [comment]
Please raise this kind of questions in the spring boot section of forum.camunda.org
