### ISSUE TITLE
No qualifying bean of type [org.camunda.bpm.spring.boot.starter.CamundaBpmProperties]

### ISSUE THREAD

**Issue by praveenbelkar** [camunda/camunda-bpm-spring-boot-starter#41]
We are creating SpringBoot gradle project with camunda-bpm dependencies in it. However when we run the Application.java - it throws following exception.

`org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.camunda.bpm.spring.boot.starter.CamundaBpmProperties] is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:371) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:331) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:968) ~[spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.camunda.bpm.spring.boot.starter.runlistener.AbstractFinishedWithNoExceptionRunListener.getBean(AbstractFinishedWithNoExceptionRunListener.java:80) ~[camunda-bpm-spring-boot-starter-1.0.0.jar:1.0.0]
	at org.camunda.bpm.spring.boot.starter.runlistener.AbstractFinishedWithNoExceptionRunListener.finished(AbstractFinishedWithNoExceptionRunListener.java:42) ~[camunda-bpm-spring-boot-starter-1.0.0.jar:1.0.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:139) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:126) [spring-cloud-context-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:75) [spring-cloud-context-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:55) [spring-cloud-context-1.0.2.RELEASE.jar:1.0.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:151) [spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:128) [spring-context-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:100) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:59) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:285) [spring-boot-1.2.5.RELEASE.jar:1.2.5.RELEASE]
	at com.emc.gs.aaa.logic.service.Application.main(Application.java:53) [bin/:na]
`

The dependencies included in build.gradle is - 
compile group: 'org.camunda.bpm.extension', name: 'camunda-bpm-spring-boot-starter', version: '1.1.0'
compile group: 'org.camunda.bpm.webapp', name: 'camunda-webapp-webjar', version: '7.4.0'

**Comment by jangalinski** [comment]
Could you provide an example project somewhere? It might get hard to reproduce since the examples prove the setup (at least using maven) basically work ...

**Comment by qihaiyan** [comment]
when importing springcloud in gradle like:
 compile("org.springframework.cloud:spring-cloud-starter-zuul")
    compile("org.springframework.cloud:spring-cloud-starter-security")
the error will be reproduced.

**Comment by jangalinski** [comment]
Ok, I will have a look

**Comment by hebbaa** [comment]
any update on this issue?

**Comment by hebbaa** [comment]
I am facing the same issue

**Comment by pixelthekid** [comment]
This is also happening for us, if we import spring cloud, Camunda will not start

**Comment by pixelthekid** [comment]
I think this is related to this fix: https://github.com/camunda/camunda-bpm-spring-boot-starter/pull/37/files

Something to do with spring cloud's parent context.

**Comment by hebbaa** [comment]
Spring cloud will create its own bootstrap application context and Tries to invoke 
org.camunda.bpm.spring.boot.starter.runlistener.AbstractFinishedWithNoExceptionRunListener
But this has got dependency of 
CamundaBpmProperties which will
not be instantiated implicitly by 
bootstrap context

To fix above 

Create directory 
META-INF/spring.factories 
Under resource directory 
And add key, value 
org.springframework.cloud.bootstrap.BootstrapConfiguration=org.camunda.bpm.spring.boot.starter.CamundaBpmProperties to
spring.factories

**Comment by jangalinski** [comment]
I added an example that adds dependency to cloud. Could reproduce the error. Fixed it by adding the cloud-bootSTrapConfiguration to the existing spring.factories. Thanks @hebbaa for the solution idea.
