### ISSUE TITLE
Autodeployment of dmn models doesn't work

### ISSUE THREAD

**Issue by ronalders** [camunda/camunda-bpm-spring-boot-starter#91]
In order to auto deploy dmn files I added dmn to deploymentResourcePattern in my application .yml file:

`camunda:
    bpm:
      autoDeploymentEnabled: true
      rest:
        enabled: true
        mappedUrl: "/rest/*"
      deploymentResourcePattern:
        - "classpath*:**/*.bpmn"
        - "classpath*:**/*.dmn"
        - "classpath*:**/*.cmmn"
`

Now thd DMN models gets picked up but it can't be deployed. It was unable to parse the file:

`org.camunda.bpm.engine.ProcessEngineException: Unable to transform DMN resource 'org.camunda.bpm.dmn'
	at org.camunda.bpm.engine.impl.dmn.deployer.DmnDeployer.transformDefinitions(DmnDeployer.java:50) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.AbstractDefinitionDeployer.transformResource(AbstractDefinitionDeployer.java:91) ~[camunda-engine-7.4.0.jar:7.4.0]
	at org.camunda.bpm.engine.impl.AbstractDefinitionDeployer.parseDefinitionResources(AbstractDefinitionDeployer.java:66) ~[camunda-engine-7.4.0.jar:7.4.0]
`

Root cause
`Caused by: org.xml.sax.SAXException: Fatal Error: URI=null Line=1: Premature end of file.
	at org.camunda.bpm.model.xml.impl.util.DomUtil$DomErrorHandler.fatalError(DomUtil.java:203) ~[camunda-xml-model-7.4.0.jar:7.4.0]
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:180) ~[na:1.7.0_51]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441) ~[na:1.7.0_51]
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368) ~[na:1.7.0_51]
`
I also upgraded tot 7.5.0 but same problem occurs when deploying DMN models. The model is correct and can be deployed in de standalone tomcat distribution. Is this a known problem or am i missing some resourcing/dependencies?

**Comment by jangalinski** [comment]
I have added dmn support in 1.2, but currently this is waiting to be released ... could you try again with the 1.2.0-SNAPSHOT version? Then you do not have to add the *dmn pattern to the config anymore, it is included automatically.

**Comment by ronalders** [comment]
@jangalinski yes that fixed the issue, it now works fine (with and without dmn pattern in mij config). It works with the following config. 

  Spring-Boot:  (v1.3.5.RELEASE)
  Camunda BPM: (v7.5.0)
  Camunda BPM Spring Boot Starter: (v1.2.0-SNAPSHOT)

When will the 1.2.0 version be released and what is in there to make it work (just curious)?

**Comment by jangalinski** [comment]
perfect.

you can check the list of issues for the 1.2 milestone here: https://github.com/camunda/camunda-bpm-spring-boot-starter/issues?q=milestone%3A1.2+is%3Aclosed

Mainly we focussed on integration of the webapp, support of 7.4. features (external tasks, dmn) and fixed some stability issues, especially when running in "the cloud".

We are ready to release, but I guess the camunda guys were a bit buisy with the 7.5 release. I am hoping for next week.
